### PR TITLE
chore: Run build on pull requests

### PR DESCRIPTION
**Pull request by msrose**
Seems like the push event only applies to repository branches https://help.github.com/en/actions/reference/events-that-trigger-workflows#push-event-push, I suspect that the pull_request event is needed to run the build on branches of forks.

UPDATE: confirmed by the fact that it's building this PR 😅

### CODE REVIEW

**Comment by msrose** [comment]
Of note: seems like it ends up running the checks twice for repository branches 🤔 https://github.com/msrose/node-package/pull/17

**Review by mcataford — APPROVED** [review]
LGTM

**Comment by mcataford** [comment]
@all-contributors please add @msrose for infra

**Pull request merged**
